infopublic_mail/blueprints/servidores/views.py
import csv
from flask import Blueprint, render_template, Response, flash
from flask_login import login_required
from infopublic_mail.extras import functions

servidor = Blueprint('servidor', __name__)
database_name = 'infopublic.db'

@servidor.route('/srv01', methods=['GET', 'POST'])
@login_required
def srv01():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 3)
    return render_template('servidores/srv01.html', records=records)

@servidor.route('/srv01/<int:sistema>', methods=['GET', 'POST'])
@login_required
def srv01_sistema(sistema):
    cursor, _  = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 3, sistema)
    return render_template('servidores/srv01_sistema.html', records=records)

@servidor.route('/srv02/<int:sistema>', methods=['GET', 'POST'])
@login_required
def srv02_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 2, sistema)
    return render_template('servidores/srv02_sistema.html', records=records)

@servidor.route('/rd_server/<int:sistema>', methods=['GET', 'POST'])
@login_required
def rdserver_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 1, sistema)
    return render_template('servidores/rdserver_sistema.html', records=records)

@servidor.route('/srv02', methods=['GET', 'POST'])
@login_required
def srv02():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 2)
    return render_template('servidores/srv02.html', records=records)

@servidor.route('/rd_server', methods=['GET', 'POST'])
@login_required
def rd_server():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 1)
    return render_template('servidores/rd_server.html', records=records)

@servidor.route('/rd_server_csv', methods=['GET', 'POST'])
@login_required
def rd_server_csv():
    cursor, _ = functions.connect(database_name)
    if functions.relatorio_servidor(cursor, 1):
        with open('relatorio.csv') as fileCsv:
            csv = fileCsv.read()
        
        return Response(
            csv,
            mimetype="text/csv",
            headers={
                "Content-disposition":"attachment; filename=relatorio_rd.csv"
            })


@servidor.route('/entidades_local/<int:sistema>', methods=['GET', 'POST'])
@login_required
def local_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 5, sistema)
    return render_template('servidores/local_sistema.html', records=records)

@servidor.route('/entidades_local', methods=['GET', 'POST'])
@login_required
def local():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 5)
    return render_template('servidores/local.html', records=records)

infopublic_mail/blueprints/views.py
import os
from flask import Blueprint, redirect, url_for, render_template, flash
from infopublic_mail.blueprints.servidores.views import rd_server
from infopublic_mail.extensions import login
from infopublic_mail.extras import functions
from infopublic_mail.extensions.forms import BuscarForm, Cadastro, EnviaButton, Cadastro_user_entidade
from infopublic_mail.extensions.email import send_email
from infopublic_mail.extensions.db import Enviados, db, Ticket
from datetime import datetime
from flask_login import login_required


bp = Blueprint("blueprints", __name__)
database_name = 'infopublic.db'


@bp.route('/cadastro', methods=['GET', 'POST'])
@login_required
def cadastro():
    form = Cadastro()
    dados = None
    if form.validate_on_submit():
        cpf = form.cpf.data
        nome = form.nome.data
        tel = form.telefone.data
        rg = form.rg.data
        email = form.email.data
        senha= form.senha.data
        ativo = form.ativo.data
        adm = form.adm.data
        cadastrado = form.cadastrado.data
        d = datetime.now()
        data = d.strftime("%d-%m-%Y - %H:%M")
        dados = dict(cpf=cpf, nome=nome, tel=tel, rg=rg, 
                    email=email, senha=senha, ativo=ativo, adm=adm, data=data,
                                                        cadastrado=cadastrado)
        cursor, conn = functions.connect(database_name)
        
        if functions.insere_usuario(cursor, conn, **dados):
            flash("Usuário cadastrado com sucesso!")
        else:
            flash("Erro ao cadastrar usuário")
    
        return redirect(url_for('blueprints.cadastro'))
        
    return render_template('cadastro.html', form=form, dados=dados)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = BuscarForm()
    tickets = Ticket.query.all()
    num_abertos = []
    num_fechados = []
    cursor, _ = functions.connect(database_name)
    records = functions.entidades_por_servidor(cursor)
    srv01 = records[2][1]
    srv02 = records[1][1]
    rd_server = records[0][1]
    local = records[3][1]
    for ticket in tickets:
        if ticket.fechado:
            num_fechados.append(ticket)
        else:
            num_abertos.append(ticket)
    if form.validate_on_submit():
        cpf = form.cpf.data
        cursor, _ = functions.connect(database_name)
        user_id = functions.cpf_retornaId(cursor, cpf)
        if user_id != None:
            return redirect(url_for('blueprints.user', id=user_id[0]))
        else:
            return render_template('404.html'), 404 
    return render_template('index.html', form=form, current_time=datetime.utcnow(),
                            num_abertos=len(num_abertos), num_fechados=len(num_fechados),
                            srv01=srv01, srv02=srv02, rd_server=rd_server, local=local)

@bp.route('/user/<int:id>', methods=['GET', 'POST'])
@login_required
def user(id):
    form = EnviaButton()
    form2 = Cadastro_user_entidade()
    cursor, conn = functions.connect(database_name)
    usuario = functions.consulta_id(cursor, id)

    telefone = None
    email = None
    pode_enviar = False
    senha_sistema = '--'

    if usuario['telefone']:
        telefone = usuario['telefone']
    if usuario['email']:
        email = usuario['email']
        pode_enviar = True
    if usuario['senha_sistema']:
        senha_sistema = usuario['senha_sistema'][0]

    cpf = usuario['cpf']
    user_id = usuario['id']
    nome = usuario['nome']
    senha = usuario['senha']
    entidades = usuario['entidades']

    if form2.validate_on_submit():
        entidade = form2.entidade.data
        senha_sistema = form2.senha_sistema.data
        dados = dict(id_user=id, entidade=entidade, senha=senha_sistema)

        if functions.insere_entidade_usuario(cursor, conn, **dados):
            flash(f'Entidade cadastrada com sucesso para {nome}')
        else:
            flash('Erro ao cadastrar entidade.') 
        return redirect(url_for('blueprints.user', id=id))

    if form.validate_on_submit():
        if pode_enviar:
            cpf_tratado = functions.trata_cpf(cpf)
            send_email(email, nome, cpf_tratado, senha, senha_sistema)
            email_enviado = Enviados(cpf=cpf_tratado, email=email)
            db.session.add(email_enviado)
            db.session.commit()
            flash('Mensagem enviada para {}'.format(email))
        else:
            flash('O campo email do usuário está vazio!')
        return redirect(url_for('blueprints.user', id=id))


    return render_template('usuario.html', id=user_id, email=email, senha=senha, entidades=entidades,
                        senha_sistema=senha_sistema, nome=nome, cpf=cpf, telefone=telefone, form=form,
                        pode_enviar=pode_enviar, form2=form2)

infopublic_mail/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-light" role="navigation" style="background-color: black">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://www.infopublic.com.br" style="color: white;">Infopublic</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('blueprints.index') }}" style="color: white;">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">    
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        {% block page_header %}{% endblock %}
    </div>
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.locale('PT') }}
{% endblock %}

infopublic_mail/templates/cadastro.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Cadastro{% endblock %}
{% block page_header %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <div>
        <p>
            <strong>OBS.:</strong> Este cadastro é realizado primeiramente no banco de dados de usuários, </br>
            apenas posteriormente, com aprovação do administrador do sistema, que o usuário </br>
            será cadastrado no servidor TS. 
        </p>
        <p>
            <strong>
                Caso o usuário já esteja cadastrado no servidor TS, basta MARCAR
                a opção 'Usuário já encontra-se cadastro no servidor?'
            </strong>
        </p>
    </div>
</div>
    <h1>Cadastro de Usuário</h1>
{% endblock %}
{% block page_content %}
    {% if dados %}
        <ul>
        {% for k, v in dados.items() %}
            <li>{{ k, v }}</li>
        </ul>
        {% endfor %}
    {% else %}
        {{ wtf.quick_form(form) }}
    {% endif %}
{% endblock %}

infopublic_mail/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Home{% endblock %}

{% block head %}
{{ super() }}
<style>
    h1,
    p {
        margin-left: 20px;
        color: black;
    }
    #cpf_busca {
        background-image: url("{{ url_for('static', filename='img/mulher_empreendedora.jpg')}}");
        background-size: cover;
        background-position: center;
    }
    #busca_form {
        color: black;
    }
    #tickets {
        background-image: url("{{ url_for('static', filename='img/mulher_branca.jpg')}}");
        background-size: cover;
        background-position: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="jumbotron" id="cpf_busca">
            <div class="row">
                <p>
            Olá,
        {% if current_user.is_authenticated %}
            <strong>{{ current_user.nome }}</strong>!
        {% else %}
            <strong>Anônimo</strong>
        {% endif %}
                </p>
            </div>
            <div class="row">
                <h1 style="color: black;">#Suporte_ Info</h1>
                <p>Envio de emails para clientes cadastrados da Infopublic</p>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ wtf.quick_form(form, id='busca_form') }}
                </div>
            </div>
            <div class="row" style="text-align: right;">
                <strong>{{ moment(current_time).format('LLL') }}</strong>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="jumbotron" id="servidores">
            <div class="container-fluid">
                <div class="row">
                    <p style="text-align: center; color: black;">
                        Servidores
                    </p>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            <a href="{{ url_for('servidor.srv01') }}">ts01-Hostdime</a>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            <a href="{{ url_for('servidor.srv02') }}">ts02-50025</a>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            <a href="{{ url_for('servidor.rd_server') }}">RD_Server</a>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            <a href="{{ url_for('servidor.local') }}">Local</a>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            {{ srv01 }}
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            {{ srv02 }}
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            {{ rd_server }}
                        </p>
                    </div>
                    <div class="col-md-3">
                        <p style="text-align: center; color: black;">
                            {{ local }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="jumbotron" id="tickets">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <p style="text-align: center;">Tickets em aberto: {{ num_abertos }}</p>
                    </div>
                    <div class="col-md-6">
                        <p style="text-align: center;">Tickets fechados: {{ num_fechados }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

infopublic_mail/templates/sucesso.html
{% extends "base.html" %}
{% block title %}cadastro{% endblock %}
{% block page_header %}
    <h1>Usuário {{ user }} cadastrado com sucesso!</h1>
{% endblock %}
{% block page_content %}
    <h2>Dados cadastrados: </h2>
    <ul>
        {% for k, v in dados %}
            <li>{{ k, v }}</li>
        {% endfor %}
    </ul>
{% endblock %}

infopublic_mail/templates/usuario.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}User {{ id }}{% endblock %}

{% block head %}
{{ super() }}
<style>
    p.info_user {
        font-weight: normal;
        font-size: 22px;
    }
</style>
{% endblock %}

{% block page_header %}
<div class="container">
    {% if pode_enviar %}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    {% else %}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
</div>
<h1>{{ nome }} <span style="float: right;">{{ cpf }}</span></h1>
{% endblock %}
{% block page_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
        <p class="info_user">id: {{ id }}</p>
        {% if email %}
            <p class="info_user">email: {{ email }}</p>
        {% endif %}
        <p class="info_user">senha: {{ senha }}</p>
        {% if senha_sistema %}
            <p class="info_user">senha sistema: {{ senha_sistema }}</p>
        {% endif %}
        {% if telefone %}
            <p class="info_user">tel: {{ telefone }}</p>
        {% endif %}
        </div>
        <div class="col-md-6">
        <table class="table">             
            <tbody class="info">
                {% for entidade in entidades %}
                    <tr class="info">
                        <td>{{ entidade[0] }}</td>
                        <td>{{ entidade[1] }}</td>
                        <td>{{ entidade[2] }}</td>
                        <td>{{ entidade[3] }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>Cadastrar entidade para <strong>{{ nome }}</strong> (apenas se você for administrador)</td>
                    <td><button type="button" onclick="mostraForm()" id="demo">Entidade</button></td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
           {{ wtf.quick_form(form) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" style="float: right;" id="form_cadastro" hidden>
            {{ wtf.quick_form(form2) }}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.getElementById("demo").onclick = mostraForm;
    
    function mostraForm(){
        document.getElementById("form_cadastro").hidden = false;
    }
        
</script>
{% endblock %}