infopublic_mail/blueprints/servidores/__init__.py
from .views import servidor

def init_app(app):
    app.register_blueprint(servidor, url_prefix='/servidores')

infopublic_mail/blueprints/servidores/views.py
import csv
from flask import Blueprint, render_template, Response, flash
from flask_login import login_required
from infopublic_mail.extras import functions

servidor = Blueprint('servidor', __name__)
database_name = 'infopublic.db'

@servidor.route('/srv01', methods=['GET', 'POST'])
@login_required
def srv01():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 3)
    return render_template('servidores/srv01.html', records=records)

@servidor.route('/srv01/<int:sistema>', methods=['GET', 'POST'])
@login_required
def srv01_sistema(sistema):
    cursor, _  = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 3, sistema)
    return render_template('servidores/srv01_sistema.html', records=records)

@servidor.route('/srv02/<int:sistema>', methods=['GET', 'POST'])
@login_required
def srv02_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 2, sistema)
    return render_template('servidores/srv02_sistema.html', records=records)

@servidor.route('/rd_server/<int:sistema>', methods=['GET', 'POST'])
@login_required
def rdserver_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 1, sistema)
    return render_template('servidores/rdserver_sistema.html', records=records)

@servidor.route('/srv02', methods=['GET', 'POST'])
@login_required
def srv02():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 2)
    return render_template('servidores/srv02.html', records=records)

@servidor.route('/rd_server', methods=['GET', 'POST'])
@login_required
def rd_server():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 1)
    return render_template('servidores/rd_server.html', records=records)

@servidor.route('/rd_server_csv', methods=['GET', 'POST'])
@login_required
def rd_server_csv():
    cursor, _ = functions.connect(database_name)
    if functions.relatorio_servidor(cursor, 1):
        with open('relatorio.csv') as fileCsv:
            csv = fileCsv.read()
        
        return Response(
            csv,
            mimetype="text/csv",
            headers={
                "Content-disposition":"attachment; filename=relatorio_rd.csv"
            })


@servidor.route('/entidades_local/<int:sistema>', methods=['GET', 'POST'])
@login_required
def local_sistema(sistema):
    cursor, _ = functions.connect(database_name)
    records = functions.gera_relatorio_sistema(cursor, 5, sistema)
    return render_template('servidores/local_sistema.html', records=records)

@servidor.route('/entidades_local', methods=['GET', 'POST'])
@login_required
def local():
    cursor, _ = functions.connect(database_name)
    records = functions.sistemas_por_servidor(cursor, 5)
    return render_template('servidores/local.html', records=records)

infopublic_mail/templates/servidores/local.html
{% extends "base.html" %}

{% block page_header %}
    <h1>Sistemas Locais<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Quantidade</th>
                    <th>ID</th>
                    <th>Sistema</th>
                {% for row in records %}
                    <tr class="info">
                        <td>{{ row[2] }}</td>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[3] }}</td>
                        <td>
                            <a href="{{ url_for('servidor.local_sistema', sistema=row[1]) }}">Ver</a>
                        </td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td><a>Gerar relatório</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/local_sistema.html
{% extends "base.html" %}

{% block page_header %}
    <h1>Sistemas Locais<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{{ url_for('servidor.local') }}">Voltar</a>
        </div>
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Código</th>
                    <th>Nome</th>
                    {% for row in records %}
                        <tr class="info">
                            <td>{{ row[0] }}</td>
                            <td>{{ row[1] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/rd_server.html
{% extends "base.html" %}

{% block page_header %}
    <h1>RD_Server<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Quantidade</th>
                    <th>ID</th>
                    <th>Sistema</th>
                {% for row in records %}
                    <tr class="info">
                        <td>{{ row[2] }}</td>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[3] }}</td>
                        <td>
                            <a href="{{ url_for('servidor.rdserver_sistema', sistema=row[1]) }}">Ver</a>
                        </td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td><a href="{{ url_for('servidor.rd_server_csv') }}">Gerar relatório</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/rdserver_sistema.html
{% extends "base.html" %}

{% block page_header %}
    <h1>RD_Server<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{{ url_for('servidor.rd_server') }}">Voltar</a>
        </div>
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Código</th>
                    <th>Nome</th>
                    {% for row in records %}
                        <tr class="info">
                            <td>{{ row[0] }}</td>
                            <td>{{ row[1] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/srv01.html
{% extends "base.html" %}

{% block page_header %}
    <h1>ts01-Hostdime<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Quantidade</th>
                    <th>ID</th>
                    <th>Sistema</th>
                {% for row in records %}
                    <tr class="info">
                        <td>{{ row[2] }}</td>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[3] }}</td>
                        <td>
                            <a href="{{ url_for('servidor.srv01_sistema', sistema=row[1]) }}">Ver</a>
                        </td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td><a>Gerar relatório</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/srv01_sistema.html
{% extends "base.html" %}

{% block page_header %}
    <h1>ts01-Hostdime<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{{ url_for('servidor.srv01') }}">Voltar</a>
        </div>
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Código</th>
                    <th>Nome</th>
                    {% for row in records %}
                        <tr class="info">
                            <td>{{ row[0] }}</td>
                            <td>{{ row[1] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/srv02.html
{% extends "base.html" %}

{% block page_header %}
    <h1>ts02-50025<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Quantidade</th>
                    <th>ID</th>
                    <th>Sistema</th>
                {% for row in records %}
                    <tr class="info">
                        <td>{{ row[2] }}</td>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[3] }}</td>
                        <td>
                            <a href="{{ url_for('servidor.srv02_sistema', sistema=row[1]) }}">Ver</a>
                        </td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td><a>Gerar relatório</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

infopublic_mail/templates/servidores/srv02_sistema.html
{% extends "base.html" %}

{% block page_header %}
    <h1>ts02-50025<h1>
{% endblock%}

{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <a href="{{ url_for('servidor.srv02') }}">Voltar</a>
        </div>
        <div class="row">
            <table class="table">
                <tbody class="info">
                    <th>Código</th>
                    <th>Nome</th>
                    {% for row in records %}
                        <tr class="info">
                            <td>{{ row[0] }}</td>
                            <td>{{ row[1] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}